// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMydYItxRKlPEDp4QFIabR2m6olEpp0e8',
    appId: '1:246996178721:web:a9280ccb2b73226e4fd060',
    messagingSenderId: '246996178721',
    projectId: 'social-application-6e8c7',
    authDomain: 'social-application-6e8c7.firebaseapp.com',
    storageBucket: 'social-application-6e8c7.firebasestorage.app',
    measurementId: 'G-DETDJ2T497',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGxYawYWcSUkejJTgjkzvI2VP3-N_9YM',
    appId: '1:246996178721:android:2f2870602fe533124fd060',
    messagingSenderId: '246996178721',
    projectId: 'social-application-6e8c7',
    storageBucket: 'social-application-6e8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvNnt2chniDxAdh8Rj5NcwczJ6WsTzEo',
    appId: '1:246996178721:ios:475b4b7202c5ead44fd060',
    messagingSenderId: '246996178721',
    projectId: 'social-application-6e8c7',
    storageBucket: 'social-application-6e8c7.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWvNnt2chniDxAdh8Rj5NcwczJ6WsTzEo',
    appId: '1:246996178721:ios:475b4b7202c5ead44fd060',
    messagingSenderId: '246996178721',
    projectId: 'social-application-6e8c7',
    storageBucket: 'social-application-6e8c7.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMydYItxRKlPEDp4QFIabR2m6olEpp0e8',
    appId: '1:246996178721:web:f131c2637195ae704fd060',
    messagingSenderId: '246996178721',
    projectId: 'social-application-6e8c7',
    authDomain: 'social-application-6e8c7.firebaseapp.com',
    storageBucket: 'social-application-6e8c7.firebasestorage.app',
    measurementId: 'G-B08HEPL5RB',
  );
}
